name: Testing Webhook Sending
on:
  workflow_dispatch:

jobs:
  plain:
    name: Execute webhook w/ plain content & embed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - uses: ./
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_USERNAME: 'Testing Webhook!'
          WEBHOOK_AVATAR: 'https://i.picsum.photos/id/483/200/200.jpg?hmac=tIKQEdwuW7trzVGWGE-cAgtpmRJla51INgO9dvJG3hA'
        with:
          content: "Hello, how's it going?"

      - uses: ./
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_USERNAME: 'Testing Webhook 2!'
          WEBHOOK_AVATAR: 'https://i.picsum.photos/id/483/200/200.jpg?hmac=tIKQEdwuW7trzVGWGE-cAgtpmRJla51INgO9dvJG3hA'
        with:
          title: 'This is an embed!'
          description: 'This is a description!'
          color: 'GREEN'
          footer: 'Brought to you by guilded.js'
          author_name: 'GuildedJS'
          author_icon: 'https://github.com/guildedjs/guilded.js/blob/main/static/guilded-icon.png?raw=true'
